### ISSUE TITLE
Node Red

### ISSUE THREAD

**Issue by Horheyx** [re-1st/HA-3d-floorplan#5]
Hello very good floor plan dashboard excellent work! 

It is possible to share the Node Red too, I like to use some of them for weather change, lights, radio, etc.

Thanks

**Comment by re-1st** [comment]
hi there! thanks for kind words mate.   
i don't think the flows are really wel made.  I am sure that,  with the proper knowledge on Node Red,  it could be done much better. I will upload them for those who want.. nonetheless
 just uploaded the weather flow .. In the folder Nodered-flows. Will upload the re later
didnt check all my flow on potentionally included passw etc.
